### ISSUE TITLE
Host name must not match method "vagrant" when trying to use tramp /vagrant:

### ISSUE THREAD

**Issue by bjbishop** [dougm/vagrant-tramp#1]
This looks like a very interesting project and I'm excited to try it out!  The vagrant ssh works great for me with my multi-VM vagrant environment, but using tramp to open files within the VM doesn't seem to work in my setup.

I'm trying this with VMware fusion 6.0.3 and emacs 24.3 on Mac OSX.  I've started emacs with a minimal setup only to include vagrant-tramp's package.

Here's how I reproduced this:

I switch the current directory in emacs to my project directory, "~/vm/mongo2" which contains a Vagrantfile with a bunch of VM's in it.  I have a VM running called "shard1" and vagrant-tramp-term connects to it fine, and works great!

I was trying to do a find-file via tramp on the VM instance using the tramp notation /vagrant:  but as soon as I type that in, I see:

Host name must not match method "vagrant"

The output of the shell script "vagrant-tramp-ssh" shows me it detected the directory name and the running instance name; it shows "mongo2-shard1" as the return result.

Thanks again for contributing this!  I'm really interested in getting this working for me as it will be a huge time-saver, how can I help?

Update: including my Vagrantfile:  https://gist.github.com/11548231

**Comment by BenjaminLawson** [comment]
I'm getting this same problem again.
