### ISSUE TITLE
vagrant-tramp can't find second running VM

### ISSUE THREAD

**Issue by 501st-alpha1** [dougm/vagrant-tramp#11]
I'm having some trouble getting `vagrant-tramp` to find my second running VM. Tested with minimal Emacs:

    emacs -Q
    M-x load-library /path/to/vagrant-tramp.el
    M-x ido-mode
    M-: (vagrant-tramp-enable)

I have two Vagrant VMs running, called e.g. `vm1` and `vm2`. I can `vagrant ssh` into either of them with no problems.

I try to find a file in the second VM with `C-x C-f /vagrant:`. At this point, it prompts me for both VMs, as it should. I start typing and select the second:

    Find file: /vagrant:vm2: [Confirm]

When I type a `/` at that point, it begins a Tramp connection, as I would expect. However, after navigating around the filesystem, I find that it did not actually connect me to the second VM, as I requested, but to the first one.

I can workaround this by `halt`ing the first VM, but it would be nice if I didn't have to do that.

Any idea why this happens?

**Comment by dougm** [comment]
This should be fixed by PR #17
