### ISSUE TITLE
vagrant-tramp-ssh not in melpa

### ISSUE THREAD

**Issue by aronatkins** [dougm/vagrant-tramp#20]
https://github.com/milkypostman/melpa/blob/master/recipes/vagrant-tramp

```
(vagrant-tramp :repo "dougm/vagrant-tramp" :fetcher github :files ("*.el" "bin"))
```

The ssh wrapper is no longer in a bin directory.

**Comment by dougm** [comment]
Moved it back to bin/ cc @ryanprior
