### ISSUE TITLE
Vagrant-tramp not always able to ssh

### ISSUE THREAD

**Issue by tylerharper** [dougm/vagrant-tramp#28]
Depending on the machine I ran vagrant-tramp it could vagrant-tramp into a machine. I would run `(find-file "/vagrant:proj_vm1:")` and I would receive the following error: 

    A Vagrant environment or target machine is required to run this
    command. Run `vagrant init` to create a new Vagrant environment. Or,
    get an ID of a target machine from `vagrant global-status` to run
    this command on. A final option is to change to a directory with a
    Vagrantfile and to try again.

The vagrant machine was running. I checked it with `vagrant global-status`. After some troubleshooting I found that the vagrant-tramp-ssh script was not getting the right machine name. This was due to the first awk statement not rebuilding $0 after $NF--. This happens on certain versions of awk.

**Comment by jdreaver** [comment]
Hey @tylerharper, I'm encountering the same error. Did you find a workaround?

**Comment by ryanprior** [comment]
I'm going to look in to this as `vagrant-tramp` has stopped working for me too, and it might be due to this same problem.

**Comment by tylerharper** [comment]
@jdreaver I had to modify the bin/vagrant-tramp-ssh. The modifications can be seen at https://github.com/tylerharper/vagrant-tramp/commit/49ca0d2047f3a83ca326012a3076cc126949a4a9.

**Comment by tylerharper** [comment]
@ryanprior I don't know if the solution is the right one, but I did find what was causing my issue.  It was the awk in [vagrant-tramp-ssh](https://github.com/dougm/vagrant-tramp/blob/master/bin/vagrant-tramp-ssh#L33). The broken chunk looks like the following:

```sh
read name dir_name <<<\
     $(echo $1 \
              | awk -F_ '{print $NF; NF--; gsub(/ /, "_", $0); print $0}')
```
The `$NF--` is removing the last field from the input (the first argument passed into the bash script). However, the `$NF--` is not rebuilding the whole input line based off of that change (awk variable `$0`).  I think `$NF--` was causing `$0` to be rebuilt automatically, but whatever version of awk we are using does not do the automatic rebuild.  You can force awk's `$0` to be rebuilt by adding a `$1 = $1` in the awk script. This has to be placed right after the `NF--;`

You can find more information in the [Changing Fields](https://www.gnu.org/software/gawk/manual/html_node/Changing-Fields.html#index-NF-variable_002c-decrementing) section of the GNU awk manual.

**Comment by jdreaver** [comment]
Hey, thanks a lot! :+1:

**Comment by stardiviner** [comment]
I have the same issue too.
Is this fix in latest release?

**Comment by stardiviner** [comment]
I tried @tylerharper 's solution, but still does not work.

**Comment by itsjeyd** [comment]
I would also like to see this fixed. @tylerharper's solution does not work for me.

**Comment by ryanprior** [comment]
I have been using Vagrant lots lately and wishing this were in better shape. I'm going to take a deep dive some time this week, as soon as time allows. Apologies to this thread for the long delay, and thank you for your comments!

**Comment by tylerharper** [comment]
@stardiviner and @itsjeyd could you show me your vagrant-tramp-ssh file?

**Comment by anonymous-octocat** [comment]
@tylerharper Sure, here it is (after applying the changes from https://github.com/tylerharper/vagrant-tramp/commit/49ca0d2047f3a83ca326012a3076cc126949a4a9):

```sh
read name dir_name <<<\
     $(echo $1 \
              | awk -F_ '{print $NF; NF--; $1 = $1; gsub(/ /, "_", $0); print $0}')

if [[ ! $name ]]; then name="default"; fi

read id dir <<<\
     $(vagrant global-status \
              | awk -v name=$name \
                    -v dir=$dir_name \
                    "\$2==name && \$5~dir { print \$1; print \$5 }")
cd "$dir"
vagrant ssh $id
```

@ryanprior That's good news! Thanks for looking into it.

**Comment by stardiviner** [comment]
Here is mine:

```sh

read name dir_name <<<\
     $(echo $1 \
              | awk -F_ '{print $NF; NF--; gsub(/ /, "_", $0); print $0}')

if [[ ! $name ]]; then name="default"; fi

read id dir <<<\
     $(vagrant global-status \
              | awk -v name=$name \
                    -v dir=$dir_name \
                    "\$2==name && \$5~dir { print \$1; print \$5 }")
cd "$dir"
vagrant ssh $id
```

**Comment by itsjeyd** [comment]
@tylerharper Sure, here it is (after applying the changes from https://github.com/tylerharper/vagrant-tramp/commit/49ca0d2047f3a83ca326012a3076cc126949a4a9):

```sh
read name dir_name <<<\
     $(echo $1 \
              | awk -F_ '{print $NF; NF--; $1 = $1; gsub(/ /, "_", $0); print $0}')

if [[ ! $name ]]; then name="default"; fi

read id dir <<<\
     $(vagrant global-status \
              | awk -v name=$name \
                    -v dir=$dir_name \
                    "\$2==name && \$5~dir { print \$1; print \$5 }")
cd "$dir"
vagrant ssh $id
```

@ryanprior That's good news! Thanks for looking into it.

**Comment by tylerharper** [comment]
@itsjeyd what version of awk are you using?

**Comment by itsjeyd** [comment]
@tylerharper I'm using version 4.1.3:

```
# pacman -Qs awk
local/gawk 4.1.3-1 (base base-devel)
    GNU version of awk
```

**Comment by stardiviner** [comment]
Mine too.

**Comment by tylerharper** [comment]
hmm. That is my version as well.  

Do your vagrant machine names have underscores in them?

**Comment by itsjeyd** [comment]
@tylerharper Are you referring to the values of the "name" column from `vagrant global-status`? If so, the answer is no:

```
id       name    provider   state    directory                                                                       
----------------------------------------------
.......  default virtualbox poweroff ...
.......  default virtualbox running  ...
.......  default virtualbox poweroff ...
.......  default virtualbox poweroff ...
.......  default virtualbox poweroff ...
.......  default virtualbox poweroff ...
.......  default virtualbox poweroff ...
.......  default virtualbox poweroff ...
.......  default virtualbox poweroff ...
.......  default virtualbox poweroff ...
.......  default virtualbox poweroff ...
.......  default virtualbox poweroff ...
.......  default virtualbox poweroff ...
.......  default virtualbox running  ...
```

**Comment by itsjeyd** [comment]
@tylerharper BTW, I very much appreciate your help! It would be great to get this working soon...

**Comment by ryanprior** [comment]
Any feedback on my updated version is appreciated.

* sidesteps the awk silliness entirely by using sed instead
* makes the system more stable by using Vagrant's machine-readable output
* uses -- instead of _ for the separator, hopefully reducing confusion.

If we could use / as a separator, that would be about perfect, since folder names can't have a slash in them. That would require a small patch to tramp, which is something I'm working on.

**Comment by stardiviner** [comment]
Problem solved, thanks. great fix.

**Comment by ryanprior** [comment]
@stardiviner the new version doesn't work on OSX. There's probably a quick fix but I don't have a Mac to test on, so for the moment I won't be able to merge this. Thank you for your help and patience. :sunflower:

**Comment by stardiviner** [comment]
If we want to make it work, might let script detect system, and use different solution. This might a good temporary way to fix it, and user can use a work version of `vagrant-tramp`. We can modify back when found the solution.
