### ISSUE TITLE
Find Vagrantfile by NFS shared folders?

### ISSUE THREAD

**Issue by tvaughan** [dougm/vagrant-tramp#9]
I have the default vagrant share disabled, and share the top-level directory via NFS. For example:

    config.vm.synced_folder '.', '/vagrant', disabled: true
    config.vm.synced_folder '.', '/opt/source', type: :nfs

Therefore this virtual machine doesn't show up in the list of available virtual machines. Does Virtualbox provide another way to locate the directory that contains the Vagrantfile besides the list of built-in shared directories?

**Comment by dougm** [comment]
Fixed by #17
